variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - checks

.rules:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE =~ /external_pull_request_event|web/

before_script:
  - export SCRIPTS_DIR=$(mktemp -d)
  - git clone -q --depth 1 "${SCRIPTS_REPO}" "${SCRIPTS_DIR}"

license:
  stage: checks
  image: licensefinder/license_finder
  script:
    - ${SCRIPTS_DIR}/git-setup
    - ${SCRIPTS_DIR}/license-check
  rules:
    - !reference [.rules, rules]

secrets:
  stage: checks
  image: docker:stable-git
  services:
    - docker:20.10.12-dind
  script:
    - ${SCRIPTS_DIR}/git-secrets
  rules:
    - !reference [.rules, rules]
