workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - checks

before_script:
  - export SCRIPTS_DIR=$(mktemp -d)
  - git clone -q --depth 1 "${SCRIPTS_REPO}" "${SCRIPTS_DIR}"

license-compliance:
  stage: checks
  image: joinself/license-finder:go
  script:
    - ${SCRIPTS_DIR}/license-check

secret-scan:
  stage: checks
  image:
    name: zricethezav/gitleaks:v8.2.4
    entrypoint: [""]
  script:
    - ${SCRIPTS_DIR}/git-secret-scan
