name: CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  secret-scan:
    uses: joinself/github-workflows/.github/workflows/secret-scan.yml@main
    secrets: inherit
  license-compliance:
    uses: joinself/github-workflows/.github/workflows/license-compliance.yml@main
    secrets: inherit
